star-pooh/keyduck

src/main/java/org/team1/keyduck/auction/entity/AuctionStatus.java
src/main/java/org/team1/keyduck/bidding/controller/BiddingController.java
src/main/java/org/team1/keyduck/bidding/dto/response/BiddingResponseDto.java
src/main/java/org/team1/keyduck/bidding/repository/BiddingRepository.java
src/main/java/org/team1/keyduck/bidding/service/BiddingService.java
src/main/java/org/team1/keyduck/member/dto/response/MemberCreateResponseDto.java

init : Add Project Common File

---

.github/workflow/main.yml
.gitignore

init : Add AI Code Reviewer

---

src/main/java/org/team1/keyduck/keyboard/entity/Keyboard.java
src/main/java/org/team1/keyduck/keyboard/service/KeyboardService.java

- 키보드 엔티티의 @Id 어노테이션 import 수정
- keyboardService.java의 테스트 코드 삭제

🚑 fix : Fix KeyboardEntity And Remove Unnecessary

---

src/main/java/org/team1/keyduck/auction/entity/Auction.java

🚑 fix : auction 테이블 경매 시작/종료일 필드명 변경

---

src/main/java/org/team1/keyduck/auction/controller/AuctionController.java
src/main/java/org/team1/keyduck/auction/dto/request/AuctionCreateRequestDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionCreateResponseDto.java
src/main/java/org/team1/keyduck/auction/entity/Auction.java
src/main/java/org/team1/keyduck/auction/service/AuctionService.java

✨ feat : 경매 생성 기능

---

src/main/java/org/team1/keyduck/auction/controller/AuctionController.java
src/main/java/org/team1/keyduck/auction/dto/request/AuctionUpdateRequestDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionUpdateResponseDto.java
src/main/java/org/team1/keyduck/auction/entity/Auction.java
src/main/java/org/team1/keyduck/auction/service/AuctionService.java

✨ feat : 경매 수정 기능 생성

---

src/main/java/org/team1/keyduck/keyboard/repository/KeyboardRepository.java
src/main/java/org/team1/keyduck/keyboard/service/KeyboardService.java

🚑 fix : 키보드 조회기능 수정

---

src/main/java/org/team1/keyduck/auction/controller/AuctionController.java
src/main/java/org/team1/keyduck/auction/dto/request/AuctionCreateRequestDto.java

1. @Vaild 어노테이션 누락으로 인해 조건 검증이 되지않는 부분 수정
2. 경매 시작일이 현재 시각이거나 현재 시각보다 이전 일수 없게 수정

🚑 fix : 경매 생성 @Vaild 어노테이션 추가

---

src/main/java/org/team1/keyduck/auction/dto/request/AuctionUpdateRequestDto.java
src/main/java/org/team1/keyduck/auction/service/AuctionService.java

1. 경매가 시작되기 전의 상태만 수정이 가능하도록 코드 수정
2. 수정 리퀘스트-> 시작일에 @future 어노테이션 추가 및 에러 메세지 추가

🚑 fix : 경매 수정 코드 변경

---

src/main/java/org/team1/keyduck/auction/service/AuctionService.java
src/main/java/org/team1/keyduck/keyboard/repository/KeyboardRepository.java

1. 삭제된 키보드로는 경매를 생성할 수 없도록 코드 수정

🚑 fix : 경매 생성 코드 수정

---

src/main/java/org/team1/keyduck/bidding/service/BiddingService.java

- 입찰가가 최소 입찰 단위 금액의 배수만큼 증가했는지 확인하도록 로직 수정

🚑 fix : Fix Bidding Price Calculate Logic

---

src/main/java/org/team1/keyduck/auction/entity/Auction.java
src/main/java/org/team1/keyduck/bidding/entity/Bidding.java
src/main/java/org/team1/keyduck/keyboard/entity/Keyboard.java
src/main/java/org/team1/keyduck/member/entity/Member.java
src/main/java/org/team1/keyduck/payment/entity/Payment.java
src/main/java/org/team1/keyduck/payment/entity/PaymentDeposit.java
src/main/java/org/team1/keyduck/payment/entity/TempPayment.java

- 모든 엔티티 속성(NOT NULL, LENGTH 등) 수정

🚑 fix : Fix Entity Attribute

---

src/main/java/org/team1/keyduck/common/exception/GlobalExceptionHandler.java

🚑 fix : Fix Parameter For Global Exception Handler

---

src/main/java/org/team1/keyduck/member/dto/response/MemberReadResponseDto.java
src/main/java/org/team1/keyduck/member/service/MemberService.java
src/main/java/org/team1/keyduck/payment/repository/PaymentDepositRepository.java

🚑 fix : 멤버 조회시 deposit 반환하도록 수정

---

src/main/java/org/team1/keyduck/auth/controller/AuthController.java
src/main/java/org/team1/keyduck/auth/dto/response/MemberCreateResponseDto.java
src/main/java/org/team1/keyduck/auth/service/AuthService.java

🚑 fix : 멤버 생성시 id 및 정보 반환

---

src/main/java/org/team1/keyduck/bidding/dto/response/BiddingResponseDto.java

:recycle: 입찰 response에 입찰 ID 추가

---

src/main/java/org/team1/keyduck/auction/dto/response/AuctionCreateResponseDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionReadAllResponseDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionReadResponseDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionUpdateResponseDto.java

테스트시 응답에 id 값이 들어오지않아 불편함 발생.
-> id 값이 들어오도록 수정

🚑 fix : 응답에 id 값이 들어오도록 수정

---

src/main/java/org/team1/keyduck/auction/dto/response/AuctionCreateResponseDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionReadAllResponseDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionReadResponseDto.java
src/main/java/org/team1/keyduck/auction/dto/response/AuctionUpdateResponseDto.java
src/main/java/org/team1/keyduck/keyboard/dto/response/AuctionKeyboardDto.java
src/main/java/org/team1/keyduck/keyboard/dto/response/KeyboardDto.java

- Response에 keyboard 의 id뿐만아닌 이름과 설명도 추가되었으면 좋겠다는 의견 반영하여 코드 수정

🚑 fix : Response에 Keyboard 정보 반영

---

src/main/java/org/team1/keyduck/auction/service/AuctionService.java
src/main/java/org/team1/keyduck/payment/service/PaymentDepositService.java

- 패찰자의 최고 입찰가를 반환해주는 로직 이동
- 기존에 경매 서비스에 위치해 있던 로직을 예치금 서비스로 이동

🔨 refactor : Refund PaymentDeposit Logic

---

src/main/java/org/team1/keyduck/auction/service/AuctionService.java
src/main/java/org/team1/keyduck/auth/service/AuthService.java
src/main/java/org/team1/keyduck/bidding/service/BiddingService.java
src/main/java/org/team1/keyduck/common/config/JwtUtil.java
src/main/java/org/team1/keyduck/common/util/Constants.java
src/main/java/org/team1/keyduck/common/util/ErrorMessage.java
src/main/java/org/team1/keyduck/common/util/ErrorMessageParameter.java
src/main/java/org/team1/keyduck/common/util/GlobalConstants.java
src/main/java/org/team1/keyduck/common/util/ValidationErrorMessage.java
src/main/java/org/team1/keyduck/keyboard/service/KeyboardService.java
src/main/java/org/team1/keyduck/member/entity/Address.java
src/main/java/org/team1/keyduck/member/entity/Member.java
src/main/java/org/team1/keyduck/member/service/MemberService.java
src/main/java/org/team1/keyduck/payment/entity/PaymentMethod.java
src/main/java/org/team1/keyduck/payment/processor/PaymentProcessorImpl.java
src/main/java/org/team1/keyduck/payment/service/PaymentDepositService.java
src/main/java/org/team1/keyduck/payment/service/PaymentService.java
src/main/java/org/team1/keyduck/payment/service/SaleProfitService.java
src/main/java/org/team1/keyduck/payment/service/TempPaymentService.java

- 중복 사용되는 에러 메시지 파라미터 정리
- 하드 코딩 되어 있는 상수값 정의

🔨 refactor : Parameter Clean Up

---

src/main/java/org/team1/keyduck/auth/service/AuthService.java
src/main/java/org/team1/keyduck/common/service/CommonService.java
src/main/java/org/team1/keyduck/member/service/MemberService.java

🔨 refactor : Duplicate Password Check Logic

---

src/main/java/org/team1/keyduck/bidding/repository/BiddingRepository.java
src/main/java/org/team1/keyduck/bidding/service/BiddingService.java

- 입찰 생성 시 이전 입찰가를 얻어오는 Jpql 메소드의 반환 타입 수정

🔨 refactor : Refactor Create Bidding Jpql Return Type

---

src/test/java/org/team1/keyduck/bidding/service/BiddingServiceTest.java

- CI/CD를 Github Action에서 H2 테스트가 실패하여 MockitoBean을 추가

🚑 fix : Add MockitoBean For CI/CD

---

.github/workflows/deploy.yml
Dockerfile
src/test/java/org/team1/keyduck/bidding/service/BiddingServiceTest.java

ver 2.1 release

---

src/main/java/org/team1/keyduck/member/repository/MemberRepository.java
src/main/java/org/team1/keyduck/member/service/MemberService.java
src/main/java/org/team1/keyduck/payment/service/PaymentService.java

결제 페이지 로그인 이후 멤버가 삭제되도 정상적으로 결제가 진행되던 문제 해결

🚑 fix : 중간에 멤버가 삭제되도 결제 되던 문제 해결

---

src/main/java/org/team1/keyduck/auth/dto/request/MemberCreateRequestDto.java
src/main/java/org/team1/keyduck/member/dto/request/MemberUpdatePasswordRequestDto.java
src/main/java/org/team1/keyduck/payment/entity/Payment.java
src/main/java/org/team1/keyduck/payment/entity/TempPayment.java

🚑 fix : 접근제어자 안붙어있던 문제 수정

---

src/main/java/org/team1/keyduck/common/config/JwtFilter.java
src/main/java/org/team1/keyduck/common/config/JwtUtil.java
src/main/java/org/team1/keyduck/common/config/SecurityConfig.java
src/main/resources/templates/payment_login.html

- 쿠키 관련 에러가 발생하지 않도록 설정 파일 수정
- JSESSIONID 쿠키의 자동 생성을 방지
- JwtUtil에서 쿠키로부터 토큰을 획득하는 로직 수정
- css 파일이 인증과 상관 없도록 수정
- 결제 로그인 화면에서 쿠키와 관련된 불필요 코드 삭제

🚑 fix : fix SecurityConfig Setting

---

src/main/java/org/team1/keyduck/auth/controller/AuthController.java
src/main/java/org/team1/keyduck/auth/service/AuthService.java
src/main/java/org/team1/keyduck/common/config/JwtFilter.java
src/main/java/org/team1/keyduck/common/config/JwtUtil.java
src/main/java/org/team1/keyduck/common/config/SecurityConfig.java
src/main/java/org/team1/keyduck/common/exception/SuccessCode.java
src/main/java/org/team1/keyduck/common/util/Constants.java
src/main/java/org/team1/keyduck/payment/controller/PaymentController.java
src/main/java/org/team1/keyduck/payment/dto/TempPaymentRequestDto.java
src/main/resources/static/token_verify.js
src/main/resources/templates/payment_fail.html
src/main/resources/templates/payment_login.html
src/main/resources/templates/payment_process.html
src/main/resources/templates/payment_success.html

- 임시 결제 정보를 저장하는 시점 변경
- 저장 시점 변경으로 인한 토큰 검증 로직 추가
- 저장 시점 변경으로 인한 불필요 코드 삭제
- 토큰 검증 로직 추가로 인한 시큐리티 설정 파일 수정

🚑 fix : Change Save Timing For Temp Payment

---

src/test/java/org/team1/keyduck/keyboard/service/KeyboardServiceTest.java

keyboardRepository 메서드 변경으로 인해 해당 메서드를 사용하던 테스트 코드 내부에서 오류가 발생하여 수정

✅ test : 키보드 조회 테스트코드 수정

---

src/main/java/org/team1/keyduck/keyboard/service/KeyboardService.java

쿼리메서드 변경 후
키보드 업데이트 서비스 로직에서 변경된 메서드로
적용되지않아 오류 발생
정상적으로 변경완료

🚑 fix : 키보드 업데이트 서비스 로직 변경

---

src/main/java/org/team1/keyduck/auction/repository/AuctionRepository.java
src/main/java/org/team1/keyduck/auction/service/AuctionService.java
src/test/java/org/team1/keyduck/testdata/TestData.java

- AuctionQueryDslRepository를 다른 곳에서 사용할 수 없는 문제로 인해 분리

🚑 fix : Separate AuctionQueryDslRepository From AuctionRepository

---

src/main/java/org/team1/keyduck/KeyduckApplication.java
src/main/java/org/team1/keyduck/auction/repository/AuctionQueryDslRepository.java
src/main/java/org/team1/keyduck/auction/repository/AuctionQueryDslRepositoryImpl.java
src/main/java/org/team1/keyduck/auction/service/AuctionService.java
src/main/java/org/team1/keyduck/common/config/SchedulerConfig.java
src/main/java/org/team1/keyduck/common/service/SchedulerService.java
src/main/java/org/team1/keyduck/common/util/Constants.java
src/test/java/org/team1/keyduck/testdata/TestData.java

- 스케줄러 기능 추가
- 경매 시작일이 되면 상태 변경 (not started -> in progress)
- 경매 종료와 동시에 진행되는 것을 생각해 스케줄러 스레드 풀 생성
- 테스트 데이터의 import 문제 해결

✨ feat : Add Auction Start Scheduler

---

.github/workflows/deploy.yml
.github/workflows/test.yml
src/main/resources/application-dev.yml
src/main/resources/application-test.yml
src/main/resources/application.yml
src/test/java/org/team1/keyduck/auction/service/AuctionCreateServiceTest.java
src/test/java/org/team1/keyduck/auction/service/AuctionServiceTest.java
src/test/java/org/team1/keyduck/bidding/service/BiddingConcurrencyTest.java
src/test/java/org/team1/keyduck/bidding/service/BiddingServiceTest.java

Revert "Hotfix/before deployment"

---

src/main/java/org/team1/keyduck/auction/service/AuctionService.java
src/main/java/org/team1/keyduck/common/util/Constants.java

오픈되었울때 -> 경매 생성자에게 오픈 알림
클로즈되었을때 -> 낙찰자에게 낙찰 알림

feat: 경매의 상태가 변했을때 이메일 알림

---

build.gradle
src/main/java/org/team1/keyduck/common/config/ShedLockConfig.java
src/main/java/org/team1/keyduck/common/service/SchedulerService.java

- 다중 인스턴스 환경에서 스케줄러 중복 실행을 방지하기 위한 Shedlock 라이브러리 추가

✨ feat : Add Shedlock For Scheduler

---

src/main/java/org/team1/keyduck/auction/repository/AuctionQueryDslRepository.java
src/main/java/org/team1/keyduck/auction/repository/AuctionQueryDslRepositoryImpl.java
src/main/java/org/team1/keyduck/auction/service/AuctionService.java
src/main/java/org/team1/keyduck/common/service/SchedulerService.java

- 트랜잭션의 보장이 제대로 동작할 수 있도록 로직 수정

🔨 refactor : Scheduler Logic
